// Morning research talks, open to everyone, from the published programme
// (Google Doc 1U-RFL5O6NNN2CpPcLmJuEVHweBT2BVhu9VaEvVsVn3w). Text as written there;
// "To be confirmed" left empty. Each gets its own page via event-collaboration-week-talk.njk.
export default [
  {
    "slug": "alessandro-favero",
    "type": "research-talk",
    "day": "Monday 5 Oct",
    "time": "09:45–10:25",
    "locationSlug": "robert-hooke-building",
    "title": "Behind the Tokens: Learning and Discovering Latent Abstractions",
    "speaker": "Alessandro Favero",
    "affiliation": "University of Cambridge",
    "abstract": "Learning from generic high-dimensional data is hopeless. Intelligence is possible only because the world has structure that can be compressed into abstractions. I will present work using simple formal grammars to understand how deep networks progressively learn hierarchical and compositional structure, and when they generalize rather than memorize. I will then show how world models that predict their own latent representations rather than raw tokens can dramatically reduce sample complexity. I will conclude with a vision for a principled science of abstraction that characterizes the concepts and computations emerging inside foundation models, connecting efficient learning, mathematical reasoning, and AI-assisted scientific discovery.",
    "bio": "Alessandro is an inaugural Physics-AI Fellow at DAMTP, University of Cambridge, the Sansom Research Associate at Emmanuel College, and a member of the Cambridge-Infosys AI Centre. His research combines theory and experiments to understand how AI learns and represents structure, often drawing on ideas from statistical physics, with current work spanning world models, compositionality, and mechanistic interpretability. He received his PhD from EPFL, where his thesis won the G-Research PhD Award in maths and data science. He collaborates with Polymathic AI on scientific foundation models and previously worked on multimodal models at Amazon's AWS AI Labs in the Bay Area."
  },
  {
    "slug": "arber-zela",
    "type": "research-talk",
    "day": "Monday 5 Oct",
    "time": "11:00–11:40",
    "locationSlug": "robert-hooke-building",
    "title": "Beyond Scale: Adaptive Computation, LLM-Guided Search and Open-Ended Discovery",
    "speaker": "Arber Zela",
    "affiliation": "EPFL",
    "abstract": "Frontier AI rests on the general recipe of training larger models on ever more data and compute. This is hitting limits: every input receives the same computation regardless of difficulty, data is finite, and models that grow with it increasingly memorize rather than generalize. What we want instead is a system that learns a rule from a few examples, a local update that, iterated, solves the task, with compute following the problem rather than the parameter count. I will start by presenting Spherical Fixed-Point Reasoners, which run a looped transformer as a fixed-point solver on the hypersphere, allocate compute adaptively across puzzle tasks, and expose the learned rule in the geometry of their internal state. Scale does not help either when LLMs act as black-box optimizers, where larger models collapse onto a few proposals. We show that search space partitioning, and combining LLMs with classical optimizers such as evolution strategies, restore competitive black-box optimization. Finally, agents in neural cellular automata also learn a local interaction rule, and evolving populations of them under novelty pressure, with the environment co-evolving alongside its learners, yields sustained complexity and cooperative structure from purely competitive dynamics. I will close with my research vision and how it aligns with BOLD's mission.",
    "bio": "Arber Zela is a postdoctoral researcher at EPFL, where he works on adaptive computation, looped models for reasoning, and LLM-based optimization. He obtained his PhD with highest distinction from the University of Freiburg as an ELLIS student, co-advised by Frank Hutter (Freiburg) and Yee Whye Teh (Oxford), with a thesis on robust, efficient and reproducible neural architecture search. He was subsequently a research scientist at the ELLIS Institute Tübingen. His research spans automated machine learning, efficient sequence models, adaptive computation and artificial life, and has appeared in more than 20 top-tier publications, including three orals at ICLR and ALIFE. He created NASLib and co-authored the NAS-Bench family of benchmarks, which reshaped evaluation practice in neural architecture search. He is an elected member of the ELLIS Society and has co-organized several workshops and competitions at leading machine learning venues."
  },
  {
    "slug": "tiago-pimentel",
    "type": "research-talk",
    "day": "Monday 5 Oct",
    "time": "11:45–12:25",
    "locationSlug": "robert-hooke-building",
    "title": "Promises and Limitations of Causality for Machine Learning Interpretability",
    "speaker": "Tiago Pimentel",
    "affiliation": "ETH Zürich",
    "abstract": "How can we move from observing what a model does to understanding why it does it? In this talk, I argue that causality is necessary but not sufficient to uncover the mechanisms underlying model predictions. First, I examine a “macro” view of model analysis, showing how econometric tools—such as regression discontinuity or difference-in-differences—can isolate the causal impact of specific design choices, like tokenisation and training-data selection, on a model’s outputs. Second, I turn to a “micro” view of mechanistic interpretability, focusing on causal abstraction as a method to establish whether a model implements a high-level algorithm. I demonstrate that this approach faces a critical limitation: without strict assumptions about how models encode information, the framework becomes vacuous, implying that any model implements any algorithm. This reveals that the ability to make counterfactual predictions about a model is not, on its own, sufficient to guarantee that we understand it. I conclude with a short discussion of how causality can be used to develop more principled interpretability methods, and with an open question about what interpretability is currently missing.",
    "bio": "Tiago Pimentel is a Postdoctoral Researcher at ETH Zürich, working at the intersection of natural language processing, interpretability, and psycholinguistics. His long-term goal is to understand how humans and machines process language. To that end, he takes an interdisciplinary approach, drawing on information theory and causality to study the mechanisms behind both model behaviour and human cognition."
  },
  {
    "slug": "alessandro-micheli",
    "type": "research-talk",
    "day": "Tuesday 6 Oct",
    "time": "09:45–10:25",
    "locationSlug": "lamb",
    "title": "EGGROLL and Gradient Flows: A Geometric View of Evolutionary Learning",
    "speaker": "Alessandro Micheli",
    "affiliation": "Imperial College London",
    "abstract": "Probability distributions play several roles in machine learning: they describe data, represent uncertainty and organise populations of candidate solutions. My research investigates how their mathematical structure can guide the construction of learning algorithms.\n\nI will illustrate this perspective through two examples from my recent work: Riemannian Neural Optimal Transport, which constructs transport maps on curved spaces using continuous neural potentials, and NeuralSurv, which combines Bayesian neural modelling with latent-variable augmentation for survival prediction under censoring.\n\nI will then turn to a preliminary connection between EGGROLL and Wasserstein gradient flows. EGGROLL learns by evaluating low-rank random perturbations of network weights. I consider evolving the joint distribution of the perturbation factors through a Wasserstein gradient flow, with the average candidate loss as its objective. Wasserstein geometry defines the cost of moving probability mass and thereby determines the direction of steepest descent in this space of distributions. Starting from independent Gaussian factors, the average candidate weights initially move in the EGGROLL update direction. This initial agreement provides a geometric interpretation of EGGROLL and motivates investigating whether continued adaptation of the factor distribution could produce new learning algorithms.\n\nBuilding on this connection, my proposed research within BOLD’s Beyond Backpropagation pillar aims to develop methods that learn from candidate evaluations without backpropagation through the network. The research will examine how to approximate these distributional dynamics while preserving efficient low-rank candidate evaluation, and whether the resulting updates improve learning enough to justify their additional computational cost.",
    "bio": "Alessandro Micheli is a Research Associate in Machine Learning at Imperial College London working on mathematically grounded machine learning, with interests spanning generative modelling, geometric learning, probabilistic methods, and AI for science. He holds a PhD in Mathematics of Random Systems from Imperial College London, completed through the Imperial–Oxford EPSRC Centre for Doctoral Training, and previously studied Part III of the Mathematical Tripos at the University of Cambridge. His recent research includes work on neural optimal transport as well as uncertainty-aware machine learning."
  },
  {
    "slug": "yongqiang-chen",
    "type": "research-talk",
    "day": "Tuesday 6 Oct",
    "time": "11:00–11:40",
    "locationSlug": "lamb",
    "title": "Toward Reliable Long-Horizon Reasoning for AI Scientist Agents",
    "speaker": "Yongqiang Chen",
    "affiliation": "MBZUAI & CMU",
    "abstract": "AI scientist agents are a north-star application of large language models. Reliable discovery requires them to reason over long horizons: infer mechanisms from imperfect observations, revise their beliefs as evidence accumulates, and retain reusable ideas that guide subsequent experiments.\n\nIn this talk, I examine three fundamental capabilities required for building reliable AI scientists. First, through an interactive benchmark, CausalGame, that imitates real-world scientific discovery, I show that existing frontier LLMs can hardly form proper beliefs from experimental observations and often confuse correlation with causation. Second, in long-horizon reasoning, imperfect belief updates can trap agents, where they stop taking informative actions to make progress. I develop T3, a principled method that restores proper credits promoting informative actions and belief updates. Finally, I present CausalEvolve, which extracts reusable high-level factors from evaluated programs, maintains them in structured memory, and uses them to guide evolutionary search. This high-level guidance improves both sample efficiency and final performance across a range of discovery tasks.\n\nTogether, these works point toward long-running agents that interpret evidence reliably, update their beliefs, and accumulate reusable knowledge. I close with directions for transferring experience across tasks and horizons for accelerated and continual discovery.",
    "bio": "Yongqiang (Andrew) Chen is a postdoctoral researcher at MBZUAI and CMU. He received his Ph.D. from CUHK in 2024. His research focuses on reliable learning, reasoning, and discovery in the open world, spanning out-of-distribution generalization, long-horizon reasoning, and LLM agents for scientific and algorithmic discovery. His research has appeared at ICML, NeurIPS, and ICLR, including oral and spotlight presentations."
  },
  {
    "slug": "michal-stefanik",
    "type": "research-talk",
    "day": "Tuesday 6 Oct",
    "time": "11:45–12:25",
    "locationSlug": "lamb",
    "title": "Plasticity Over Scale: Objectives and Gradient-Free Adaptation for Open-Ended Learning",
    "speaker": "Michal Štefánik",
    "affiliation": "National Institute of Informatics, Japan",
    "abstract": "In this talk, I will make a case for two directions in which AI models can acquire new capabilities beyond scale: rethinking the features of commonly used training objectives, and making existing models more adaptable without updating their weights.\n\nOur prior work evidences that modelling the irreducible uncertainty in training data often leads to decays in robustness, manifesting as reasoning shortcuts and data-specific artefacts. I will show how a better treatment of uncertainty in training equips models with more plasticity, fully eliminating the reliance of instruction-tuned LLMs on known shortcuts and cutting catastrophic forgetting by 85–96% in language generation.\n\nIn the second part, I show how understanding models' internal mechanisms opens up improvements beyond scale. Accurate readouts of internal representations expose where a model's computation goes wrong and let us fix it, with no gradient update, by changing the path through its layers, cutting arithmetic errors by up to 64%. Building on that, I will present parts of our ongoing work on Dynamic Routing Models, demonstrating the potential of nonlinear inference for gradient-free adaptation that pushes existing models beyond chain-of-thought performance.\n\nI will close with my vision for BOLD as a unique opportunity to build a lab with a culture that fully harnesses open-ended discovery.",
    "bio": "Michal Štefánik is a Specially Appointed Researcher at the R&D Centre for Large Language Models at the National Institute of Informatics (NII), Japan, working in the team of Pontus Stenetorp (NII/UCL). His research mission is to understand what makes language models robust and versatile, and to apply that understanding to build more reliable and adaptable AI models. He holds a PhD from Masaryk University, recognised by several awards, including the Informatics Europe Best Dissertation Award, and has first-authored 10 papers in different tracks of ACL, EMNLP, and NeurIPS. Before the positions at the University of Helsinki and NII, he also spent ten years in industry, latterly leading the NLP research team at Gauss Algorithmic. Since 2020, he has founded and led TransformersClub, a distributed platform that supports and connects students excited about research. He is currently the lead organiser of the NeurIPS 2026 AIMO Interpretability Challenge."
  },
  {
    "slug": "veronica-alvarez",
    "type": "research-talk",
    "day": "Wednesday 7 Oct",
    "time": "09:00–09:45",
    "locationSlug": "thom-building",
    "title": "Supervised Learning with Evolving Tasks",
    "speaker": "Verónica Álvarez",
    "affiliation": "MIT",
    "abstract": "Multiple supervised learning scenarios are composed by a sequence of classification tasks. For instance, multi-task learning and continual learning aim to learn a sequence of tasks that is either fixed or grows over time. Existing techniques for learning tasks that are in a sequence are tailored to specific scenarios, lacking adaptability to others. In addition, most of existing techniques consider situations in which the order of the tasks in the sequence is not relevant. However, it is common that tasks in a sequence are evolving in the sense that consecutive tasks often have a higher similarity. This paper presents a learning methodology that is applicable to multiple supervised learning scenarios and adapts to evolving tasks. Differently from existing techniques, we provide computable tight performance guarantees and analytically characterize the increase in the effective sample size. Experiments on benchmark datasets show the performance improvement of the proposed methodology in multiple scenarios and the reliability of the presented performance guarantees.",
    "bio": "Verónica Álvarez is a postdoctoral researcher at MIT working on reliable and adaptive machine learning under distribution shift. Her research combines statistical learning theory, online and federated learning, and probabilistic modeling, with a focus on developing learning systems that can adapt to changing environments while providing performance guarantees. She received her PhD in Computer Engineering from the Basque Center for Applied Mathematics (BCAM), and has been recognized with several awards for her research, including the 2025 SCIE–BBVA Foundation Award for Young Researchers in Computer Science and the 2024 Best PhD Thesis in Informatics and AI Award from the Spanish Society of AI."
  },
  {
    "slug": "christos-ziakas",
    "type": "research-talk",
    "day": "Wednesday 7 Oct",
    "time": "09:45–10:25",
    "locationSlug": "thom-building",
    "title": "Adapting Foundation Models Beyond Pre-training: From Autoresearch to Embodied AI",
    "speaker": "Christos Ziakas",
    "affiliation": "Imperial College London",
    "abstract": "Autoresearch agents tackle problems with no known optimum by repeatedly proposing candidate solutions, evaluating them, and using feedback to guide subsequent experiments. A single autoresearch run can evaluate hundreds of candidate solutions and continue for multiple days, raising a fundamental question: over such long horizons, does an agent explore the solution space broadly? In this talk, I will provide evidence that frontier LLM agents mainly refine the ideas they selected early on, showing that independent runs plateau in distinct \"idea basins\" within the solution space. To help agents escape these basins, I will introduce branch-reset, a test-time intervention that consistently improves performance across long-horizon research and engineering tasks. Just as autoresearch agents should explore beyond their initial idea basins, embodied agents should generalize beyond imitating expert demonstrations by learning from their own experience. To this end, I will present how to effectively adapt offline RL policies via environment interaction under a principled framework for one-step flow-matching policies, achieving state-of-the-art performance in offline-to-online RL. Building on the theme of adapting generative foundation models beyond pre-training, I will finally discuss test-time methods across language and vision modalities, along with future directions toward advancing scientific discovery and embodied AI via test-time adaptation and open-ended learning.",
    "bio": "Christos is a Marie Skłodowska-Curie Doctoral Fellow at Imperial College London, advised by Prof. Alessandra Russo and Prof. Joey Bose. His research interests focus on test-time adaptation and post-training for generative foundation models to advance automated scientific research and embodied AI. He did a research internship at Microsoft Research AI Frontiers in New York and worked at Microsoft AI on post-training Copilot 365 for tool use. Before pursuing a PhD in AI, he co-founded Athina AI (YC W23), an LLM observability startup."
  },
  {
    "slug": "valeria-ruscio",
    "type": "research-talk",
    "day": "Wednesday 7 Oct",
    "time": "11:00–11:40",
    "locationSlug": "thom-building",
    "title": "The Cost of Training: how cross-entropy shapes a transformer's geometry",
    "speaker": "Valeria Ruscio",
    "affiliation": "Intuition Machines",
    "abstract": "Autoregressive generation is an effective way to generate text, and training it with cross-entropy (CE) against one-hot targets, through a softmax, seems to be the best approach we have. Like every choice, it has costs, and this talk follows my research through four of them: at the output, in the weights, over time as the model keeps learning, and in what the loss itself cannot see.\n\nThe first cost is at the output: CE is minimised at the vertices of the probability simplex, so it pulls a model's distribution toward one-hot answers regardless of how much uncertainty the network registers internally, and much of what we call overconfidence is the gap between what a model detects and what it is trained to express. The second is in the weights: one-hot targets make every per-sample gradient point at a vertex of the simplex, and these sharp signals accumulate anisotropically: pretraining installs prediction geometry in the matrices that write to the residual stream, while alignment, lacking that sharpness, concentrates in those that read from it, a prediction confirmed by a closed-form rank-one edit with matched controls. The third appears over time: a softmax over the whole vocabulary means that when a model keeps learning, probability can leave an old answer set entirely rather than move within it, and splitting Adam's update into current gradient and accumulated history shows that history drives this leakage while the current gradient protects against it. The last is in what the loss can see. Because cross-entropy reaches the internal computation only through the final logits, it cannot tell an answer that never formed from one that formed and lost, which is why I built an exact accounting of a forward pass that can.\n\nNone of this is necessarily something we strictly need to fix; cross-entropy has earned its place. But the more we know about what the training regime does to the architecture and to the knowledge it encodes, the more informed our choices will be when we design what comes next.",
    "bio": "Valeria Ruscio is a research scientist at Intuition Machines, where she works on the mechanistic interpretability and training dynamics of large language models through the lens of geometry. Her research studies the internal mechanisms of transformers, from the structures that attention builds to organise its representations and the role of positional encodings in shaping them, to the way training distributes change across the weights of the network, the mechanisms behind factual errors and overconfidence, and the loss of previously acquired behaviour when a model keeps learning. Underlying all of this is a single question, which is how the way we train a model shapes its geometry, in the weights and in the representations they produce. Before joining Intuition Machines she was a postdoctoral researcher at Sapienza University of Rome, where her work focused on positional encodings and on how position shapes a transformer's internal processing, with a visiting period at the University of Cambridge; her PhD, also at Sapienza, applied spectral methods and signal processing to the interpretability of language models. Her expertise is on large language models, with some experience of diffusion language models and state-space models, and she is glad to work on other architectures too, particularly the deep and complex ones where interpretability is the real challenge."
  },
  {
    "slug": "paul-duckworth",
    "type": "research-talk",
    "day": "Wednesday 7 Oct",
    "time": "11:45–12:25",
    "locationSlug": "thom-building",
    "title": "Latent Space Bayesian Optimisation for Budget-Constrained Protein Design",
    "speaker": "Paul Duckworth",
    "affiliation": "InstaDeep",
    "abstract": "",
    "bio": "Paul is a senior researcher at InstaDeep (UK) with combined postdoctoral and industry research experience. He built and leads a research team focused on decision-making for biologics, specialising in budget constrained data acquisition and model adaptation. His core expertise spans probabilistic machine learning, active learning, Bayesian optimisation, generative model steering and fine-tuning."
  },
  {
    "slug": "jixiang-qing",
    "type": "research-talk",
    "day": "Thursday 8 Oct",
    "time": "09:00–09:45",
    "locationSlug": "thom-building",
    "title": "Sequential Decision-Making under Uncertainty: From Bayesian Optimisation to Open-Ended Discovery",
    "speaker": "Jixiang Qing",
    "affiliation": "Lancaster University",
    "abstract": "Many real-world learning and decision problems involve costly interactions with black-box systems, leaving limited opportunities to experiment. In this talk, I will present my approaches to such problems across different settings, tracing a progression from Bayesian optimisation and active learning towards sequential decision-making under uncertainty. Along this progression, I will show how uncertainty and prior experience can be used to choose more informative interactions, from stateless optimisation and learning problems to state-dependent sequential settings. Building on this, I will discuss how this perspective could contribute to BOLD’s Human-Centric Learning & Discovery pillar, including more open-ended forms of scientific discovery.",
    "bio": "Jixiang Qing is a Lecturer in Mathematical AI at Lancaster University. His research focuses on sample efficient decision making under uncertainty, with particular interests in Bayesian optimisation, active learning, and sequential decision-making for real-world systems. Before joining Lancaster in October 2025, he was a postdoctoral researcher at Imperial College London and completed his PhD at Ghent University in 2023."
  },
  {
    "slug": "javad-maheri",
    "type": "research-talk",
    "day": "Thursday 8 Oct",
    "time": "09:45–10:25",
    "locationSlug": "thom-building",
    "title": "Universally Optimal Combinatorial Schemes for Distributed Computing and Learning in privacy amplification",
    "speaker": "Javad Maheri",
    "affiliation": "EURECOM",
    "abstract": "Many of the hardest problems in distributed computing and learning come down to one question: how should data and tasks be placed across machines so that computation happens with as little communication as possible? In this talk, I show that combinatorial designs such as Steiner-type systems, interweaved-clique constructions, and hypergraph partitions give exact, non-asymptotic answers to this question. They yield schemes that are universally optimal, meaning the same placement is optimal regardless of the task, with explicit finite-size constants rather than scaling laws.\n\nI then argue that the same combinatorial structure is a natural foundation for privacy. The properties that make a design communication-optimal also control what each server, user, or eavesdropper can observe. Those properties are balanced overlaps, symmetric coverage, and controlled intersections. I'll outline how these designs connect to private information retrieval, coded caching with private demands, and secure aggregation in federated learning. I'll also identify where exact combinatorial limits could replace today's order-optimal privacy–communication trade-offs. The goal is a unified view in which privacy guarantees and communication cost are designed together, from the same combinatorial object.",
    "bio": "Javad Maheri received his PhD from EURECOM / Sorbonne Université in 2026 under the supervision of Prof. Petros Elia. His thesis was titled \"Universally Optimal Combinatorial Schemes for Distributed Computing and Learning.\" His research develops combinatorial designs, including Steiner-inspired systems, interweaved-clique constructions, and hypergraph partitioning, to derive exact communication limits for distributed computing, coded caching, and learning. His work has appeared in IEEE Transactions on Information Theory and at ISIT. He previously earned a double-major B.Sc. in Electrical Engineering and Mathematics, with high honors, from Sharif University of Technology."
  },
  {
    "slug": "zhangyue-yin",
    "type": "research-talk",
    "day": "Thursday 8 Oct",
    "time": "11:00–11:40",
    "locationSlug": "thom-building",
    "title": "Title to be confirmed",
    "speaker": "Zhangyue Yin",
    "affiliation": "",
    "abstract": "",
    "bio": ""
  },
  {
    "slug": "vincent-herrmann",
    "type": "research-talk",
    "day": "Thursday 8 Oct",
    "time": "11:45–12:25",
    "locationSlug": "thom-building",
    "title": "What is Worth Discovering? Computational Principles for Open-Ended AI",
    "speaker": "Vincent Herrmann",
    "affiliation": "IDSIA, USI & KAUST",
    "abstract": "AI systems have become amazingly capable at learning from large datasets, solving given problems, achieving clear tasks, and reaching specific goals. More open-ended forms of intelligence, however, must also be able to decide what to learn or which tasks to tackle. This talk asks whether the required notion of scientific \"taste\" or interestingness can be given a computational foundation. I will first present a formal view of interestingness as a prospective heuristic for future compression progress, and show how the trajectory of past compression progress can predict the potential for further insight. I will then describe practical methods for measuring the complexity and interestingness of in-context computation in neural sequence models, and show how LLMs can be actively steered towards more creative outputs. Alongside this, my work on neural weight space representations explores how behaviours, policies, and experiments themselves can be directly generated and evaluated. Building on these ideas, I propose a research programme on the computational principles of open-ended discovery. For a safe and prosperous collaboration between human and artificial scientists, we must understand both the fundamental limitations and the conditions required for AI systems to continuously propose, select, test, and refine their own learning opportunities.",
    "bio": "Vincent Herrmann is a machine learning researcher at the Swiss AI Lab IDSIA and Università della Svizzera italiana, where he completed his PhD under the supervision of Jürgen Schmidhuber. His research focuses on artificial curiosity, large language models, reinforcement learning, weight-space learning, and information theory. His work has appeared as first-author oral and paper contributions at top-tier venues including ICML, ICLR, NeurIPS, AAAI, and IEEE TPAMI. Vincent's honours include the NeurIPS 2019 Outstanding Demonstration Award as the sole recipient, recognition as a KAUST Rising Star in AI, and workshop best paper awards. He is also a Research Consultant at KAUST and has taught several courses on deep learning, generative modeling, and creative AI. Besides computer science, he has a background in classical piano performance and composition."
  },
  {
    "slug": "caroline-mazini-rodrigues",
    "type": "research-talk",
    "day": "Friday 9 Oct",
    "time": "09:00–09:45",
    "locationSlug": "rhodes-house",
    "title": "Interpretability for global understanding and frugality",
    "speaker": "Caroline Mazini Rodrigues",
    "affiliation": "CNRS",
    "abstract": "Deep learning models achieve strong performance across different tasks, but their increasing complexity introduces challenges related to transparency, interpretability, and computational efficiency. Explainable Artificial Intelligence (XAI) provides tools to better understand how these models behave, including post-hoc explanation methods that show feature contributions to model predictions without modifying the architecture. In this talk, I will present two axes of my research aiming at understanding and simplifying models.  First, I study how post-hoc XAI techniques can be used to improve the global interpretability of models, with contributions including MAGE and XAiTrees. Second, I use Jacobian analysis to investigate the behavior of image compression autoencoders and identify patterns across different inputs, providing insights into reducing model complexity and computational costs while preserving performance.",
    "bio": "Caroline Mazini Rodrigues is a CNRS postdoctoral researcher at the Institut de Recherche en Informatique et Systèmes Aléatoires (IRISA), where she develops low-complexity algorithms for video compression networks, aiming for simplicity, interpretability, and frugality in AI models. She earned her PhD from Université Gustave Eiffel, conducting research at the Laboratoire d’Informatique Gaspard-Monge (LIGM) and the Laboratoire de Recherche de l'EPITA (LRE) on explainable Artificial Intelligence (XAI), with a particular focus on understanding the reasoning processes of deep neural networks. Her research interests include making AI more transparent, frugal, and human-interpretable, while exploring and analyzing different machine learning architectures, including diffusion models and compression techniques."
  },
  {
    "slug": "rachel-freedman",
    "type": "research-talk",
    "day": "Friday 9 Oct",
    "time": "09:45–10:25",
    "locationSlug": "rhodes-house",
    "title": "Learning from diverse teachers: expertise, values, and adaptation in reward learning",
    "speaker": "Rachel Freedman",
    "affiliation": "UC Berkeley",
    "abstract": "Reward learning methods such as RLHF typically assume that feedback comes from a single, consistent teacher, yet in practice it comes from many people who differ in expertise, disagree about values, and change their views over time. I first show how modelling differences in teacher rationality lets a learner choose which teachers to query and when, improving the accuracy and efficiency of reward learning. I then present Adaptive Pluralistic Alignment (APA), a modular pipeline for efficiently updating pluralistically aligned AI systems to track evolving values and avoid value lock-in. APA represents a population as a jury of personalised reward models, aggregates their judgements with voting rules from social choice theory, and adapts to shifting values without retraining the underlying model. Finally, I outline how these methods could support a human-in-the-loop co-scientist that must decide whose feedback to trust, reconcile disagreement among its collaborators, and remain auditable as its team's goals evolve.",
    "bio": "Rachel Freedman is a final-year PhD candidate in Artificial Intelligence at UC Berkeley's Center for Human-Compatible AI, where she is advised by Professor Stuart Russell and holds a Cooperative AI Foundation PhD Fellowship. Her research focuses on scalable supervision, pluralistic alignment and reward learning. She was previously a Robertson Scholar at Duke University, a visiting student at the University of Oxford and a visiting researcher at the University of Cambridge."
  },
  {
    "slug": "jindong-gu",
    "type": "research-talk",
    "day": "Friday 9 Oct",
    "time": "11:00–11:40",
    "locationSlug": "rhodes-house",
    "title": "Title to be confirmed",
    "speaker": "Jindong Gu",
    "affiliation": "",
    "abstract": "",
    "bio": ""
  },
  {
    "slug": "mikhail-burtsev",
    "type": "research-talk",
    "day": "Friday 9 Oct",
    "time": "11:45–12:25",
    "locationSlug": "rhodes-house",
    "title": "Frontiers of Open-Ended Learning",
    "speaker": "Mikhail Burtsev",
    "affiliation": "London Institute for Mathematical Sciences",
    "abstract": "A discovery can change both what we know and what we are able to discover next. What allows this process to continue? How do adaptive systems generate new capabilities, preserve useful innovations, and create opportunities for further learning? This talk explores these questions across biological evolution and artificial intelligence. I will connect studies of emerging cooperation in artificial life and the interplay between learning and evolution with recent advances in memory architectures for AI. A central theme is how memory turns transient experience into reusable knowledge that can guide future behaviour. I will introduce the predictability frontier: what a system can reliably predict or control within a given resource budget. This framework connects the acquisition of individual capabilities to broader questions about open-ended learning, the growth of adaptive complexity and recursive self-improvement. Experiments in virtual biological systems could make these questions testable, allowing agents to infer mechanisms, choose interventions and build on earlier discoveries. The central challenge is to understand when accumulated knowledge improves the process of discovery itself, enabling learning systems to expand their own possibilities.",
    "bio": "Mikhail Burtsev is an Arnold and Landau AI Fellow at the London Institute for Mathematical Sciences. His research explores how natural and artificial systems acquire, retain and combine knowledge, spanning artificial life, evolutionary learning, neural memory and genomic foundation models. His current work focuses on open-ended learning and the conditions under which accumulated knowledge enables further discovery."
  }
];
