// Day-by-day shape of the BOLD Collaboration Week programme (5–9 Oct 2026),
// following the published programme (see collabWeekResearchTalks.js) and the
// programme spreadsheet (see collabWeekSessions.js for the source links).
// Block kinds: `sessions` (slugs into collabWeekSessions.js — a keynote's slug
// is its talk's, collabWeekResearchTalks.js; more than one = in parallel),
// `logistics` (plain text: arrival, breaks, meals).
export default {
  days: [
    {
      date: '2026-10-05',
      label: 'Monday 5 Oct',
      blocks: [
        { time: '09:00–09:45', kind: 'sessions', sessions: ['welcome-monday'] },
        { time: '09:45–10:25', kind: 'sessions', sessions: ['alessandro-favero'] },
        { time: '10:30–11:00', kind: 'logistics', label: 'Break' },
        { time: '11:00–11:40', kind: 'sessions', sessions: ['arber-zela'] },
        { time: '11:45–12:25', kind: 'sessions', sessions: ['tiago-pimentel'] },
        { time: '12:30–13:45', kind: 'logistics', label: 'Lunch · Natural History Museum' },
        { time: '13:45–14:05', kind: 'sessions', sessions: ['membrane-free-research-organisation'] },
        { time: '14:05–15:00', kind: 'sessions', sessions: ['monday-keynote-and-pillars'] },
        { time: '15:00–15:30', kind: 'logistics', label: 'Break' },
        { time: '15:30–16:45', kind: 'sessions', sessions: ['project-pitches-i'] },
        { time: '16:45–17:30', kind: 'sessions', sessions: ['after-agi-panel'] },
        { time: '18:00–19:30', kind: 'logistics', label: 'Dinner · casual gathering at the pub (details to be confirmed)' },
      ],
    },
    {
      date: '2026-10-06',
      label: 'Tuesday 6 Oct',
      blocks: [
        { time: '08:00–09:00', kind: 'logistics', label: 'Arrival & coffee · LaMB' },
        { time: '09:00–09:45', kind: 'sessions', sessions: ['welcome-tuesday'] },
        { time: '09:45–10:25', kind: 'sessions', sessions: ['alessandro-micheli'] },
        { time: '10:30–11:00', kind: 'logistics', label: 'Break' },
        { time: '11:00–11:40', kind: 'sessions', sessions: ['yongqiang-chen'] },
        { time: '11:45–12:25', kind: 'sessions', sessions: ['michal-stefanik'] },
        { time: '12:30–13:45', kind: 'logistics', label: 'Lunch · LaMB Lecture Theatre' },
        { time: '13:45–15:00', kind: 'sessions', sessions: ['research-to-entrepreneurship', 'bold-os-workshop'] },
        { time: '15:00–15:30', kind: 'logistics', label: 'Break' },
        { time: '15:30–17:30', kind: 'sessions', sessions: ['ai4science-bold', 'proving-isnt-understanding', 'bold-os-workshop-continued'] },
        { time: '18:00–19:30', kind: 'logistics', label: 'Dinner · casual gathering at the pub (details to be confirmed)' },
      ],
    },
    {
      date: '2026-10-07',
      label: 'Wednesday 7 Oct',
      blocks: [
        { time: '08:00–09:00', kind: 'logistics', label: 'Arrival & coffee · Thom Building' },
        { time: '09:00–09:45', kind: 'sessions', sessions: ['veronica-alvarez'] },
        { time: '09:45–10:25', kind: 'sessions', sessions: ['christos-ziakas'] },
        { time: '10:30–11:00', kind: 'logistics', label: 'Break' },
        { time: '11:00–11:40', kind: 'sessions', sessions: ['valeria-ruscio'] },
        { time: '11:45–12:25', kind: 'sessions', sessions: ['paul-duckworth'] },
        { time: '12:30–13:45', kind: 'logistics', label: 'Lunch · Thom Building Lecture Theatre (please finish by 13:30)' },
        { time: '13:45–15:00', kind: 'sessions', sessions: ['who-do-you-trust', 'co-scientist-future-of-human-involvement'] },
        { time: '15:00–15:30', kind: 'logistics', label: 'Break' },
        { time: '15:30–17:30', kind: 'sessions', sessions: ['reward-models-for-llms', 'open-ended-multi-agent-env-design'] },
        { time: '18:00–19:30', kind: 'logistics', label: 'Drinks & dinner for everyone · Rhodes House' },
      ],
    },
    {
      date: '2026-10-08',
      label: 'Thursday 8 Oct',
      blocks: [
        { time: '08:00–09:00', kind: 'logistics', label: 'Arrival & coffee · Thom Building' },
        { time: '09:00–09:45', kind: 'sessions', sessions: ['jixiang-qing'] },
        { time: '09:45–10:25', kind: 'sessions', sessions: ['javad-maheri'] },
        { time: '10:30–11:00', kind: 'logistics', label: 'Break' },
        { time: '11:00–11:40', kind: 'sessions', sessions: ['zhangyue-yin'] },
        { time: '11:45–12:25', kind: 'sessions', sessions: ['vincent-herrmann'] },
        { time: '12:30–13:45', kind: 'logistics', label: 'Lunch · Thom Building Lecture Theatre' },
        { time: '13:45–15:00', kind: 'sessions', sessions: ['after-agi-what-is-left', 'tabular-foundation-models', 'reasoning-generalisation-world-models'] },
        { time: '15:00–15:30', kind: 'logistics', label: 'Break' },
        { time: '15:30–17:30', kind: 'sessions', sessions: ['rethinking-ml-conferences', 'eggroll', 'memory-for-long-horizon-agents'] },
        { time: '18:30–19:30', kind: 'logistics', label: 'Dinner · casual gathering at the pub (details to be confirmed)' },
      ],
    },
    {
      date: '2026-10-09',
      label: 'Friday 9 Oct',
      blocks: [
        { time: '08:00–09:00', kind: 'logistics', label: 'Arrival & coffee · Rhodes House' },
        { time: '09:00–09:45', kind: 'sessions', sessions: ['caroline-mazini-rodrigues'] },
        { time: '09:45–10:25', kind: 'sessions', sessions: ['rachel-freedman'] },
        { time: '10:30–11:00', kind: 'logistics', label: 'Break' },
        { time: '11:00–11:40', kind: 'sessions', sessions: ['jindong-gu'] },
        { time: '11:45–12:25', kind: 'sessions', sessions: ['mikhail-burtsev'] },
        { time: '12:30–13:45', kind: 'logistics', label: 'Lunch · Rhodes House' },
        { time: '13:45–15:00', kind: 'sessions', sessions: ['opening-the-black-box', 'bold-os-follow-up'] },
        { time: '15:00–15:30', kind: 'logistics', label: 'Break' },
        { time: '15:30–17:30', kind: 'sessions', sessions: ['multi-agent-research-at-bold', 'goals-options-structured-actions'] },
      ],
    },
  ],
};
